select distinct PRODUCTS.PRODUCT_ID from PRODUCTS inner join ORDERS
on PRODUCTS.PRODUCT_ID in
(select distinct ORDERS.PRODUCT from ORDERS inner join SALESREPS
on ORDERS.REP in
(select distinct SALESREPS.EMPL_NUM from OFFICES inner join SALESREPS on
SALESREPS.REP_OFFICE = OFFICES.OFFICE except
(select OFFICES.OFFICE from OFFICES
where OFFICES.REGION like 'Eastern')))

select SALESREPS.NAME, AVG(ORDERS.AMOUNT/ORDERS.QTY) [average price] from 
SALESREPS inner join ORDERS on ORDERS.REP = SALESREPS.EMPL_NUM
group by SALESREPS.NAME
having AVG(ORDERS.AMOUNT/ORDERS.QTY) > 600