select distinct PULPIT.PULPIT_NAME from PULPIT 
inner join FACULTY
on PULPIT.FACULTY = FACULTY.FACULTY
inner join PROFESSION
on PROFESSION.FACULTY = PULPIT.FACULTY
where PROFESSION.PROFESSION_NAME like '%технология%' or PROFESSION.PROFESSION_NAME like '%технологии%'
